### ISSUE TITLE
stripped zoom example

### ISSUE THREAD

**Issue by coderofsalvation** [dmotz/trystero#60]
Hi,

First of all: thanks!<br> 
Thanks for leading us out of the dark ages of p2p/webrtc which require plumbing a signalling-server together.
This has really been holding back the p2p movement in a certain sense (people don't like too much moving parts).
With all the common good online infrastructure (bittorrent e.g.), a signaling 'commons' was really something I was hoping for (but didn't had the skills to develop something like this).

Anyways, it works like a charm.
I've re-created the README.md example-snippets into a stripped zoom-client:

https://gist.github.com/coderofsalvation/b70d635061220f2860f21eb69c8e5918

Feel free to use it.

> Idea: put it in the repo as `example/zoom.html` and add the following `.github/workflows/website.yml`:

```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

* activate github pages in settings
* Optionally put an index.html landingpage in the root of the repo

> Boom..you have a project/demos which people can check out with one click
